name: Contract Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: la
      - run: yarn install
      - run: yarn ganache &
      - run: yarn test
      - run: yarn type-gen
      - run: rm -rf build contracts migrations test
