name: Contract Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          check-latest: true
          cache: "yarn"
      - run: yarn install
      - run: mv ./.env.sample ./.env
      - run: yarn ganache &
      - run: yarn test
      - run: yarn type-gen
